CREATE TABLE Person (
	Id NUMBER(10) NOT NULL PRIMARY KEY,
	MergedToPersonId NUMBER(10),
	FirstName VARCHAR2(50),
	LastName VARCHAR2(50),
	SupervisorId NUMBER(10),
	CareerCounselorId NUMBER(10),
	CreateDate DATE
)
/

CREATE SEQUENCE PERSON_ID_SEQ START WITH 5
/

CREATE TABLE Company (
	Id NUMBER(10) NOT NULL PRIMARY KEY,
	Name VARCHAR2(100)
)
/

CREATE SEQUENCE COMPANY_ID_SEQ START WITH 3
/

CREATE TABLE PersonCompany (
	Id NUMBER(10) NOT NULL PRIMARY KEY,
	PersonId NUMBER(10) NOT NULL,
	CompanyId NUMBER(10) NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE
)
/

CREATE SEQUENCE PERSONCOMPANY_ID_SEQ START WITH 6
/

CREATE TABLE Email (
	Id NUMBER(10) NOT NULL PRIMARY KEY,
	Address VARCHAR2(250)
)
/

CREATE SEQUENCE EMAIL_ID_SEQ START WITH 7
/

CREATE TABLE PersonEmail (
	Id NUMBER(10) NOT NULL PRIMARY KEY,
	PersonId NUMBER(10) NOT NULL,
	EmailId NUMBER(10) NOT NULL
)
/

CREATE SEQUENCE PERSONEMAIL_ID_SEQ START WITH 5
/

CREATE TABLE CompanyEmail (
	Id NUMBER(10) NOT NULL PRIMARY KEY,
	CompanyId NUMBER(10) NOT NULL,
	EmailId NUMBER(10) NOT NULL
)
/

CREATE SEQUENCE COMPANYEMAIL_ID_SEQ START WITH 3
/

CREATE TABLE Phone (
	Id NUMBER(10) NOT NULL PRIMARY KEY,
	"Number" VARCHAR2(16),
	"Type" NUMBER(10)
)
/

CREATE SEQUENCE PHONE_ID_SEQ START WITH 6
/

CREATE TABLE PersonPhone (
	Id NUMBER(10) NOT NULL PRIMARY KEY,
	PersonId NUMBER(10) NOT NULL,
	PhoneId NUMBER(10) NOT NULL
)
/

CREATE SEQUENCE PERSONPHONE_ID_SEQ START WITH 4
/

CREATE TABLE CompanyPhone (
	Id NUMBER(10) NOT NULL PRIMARY KEY,
	CompanyId NUMBER(10) NOT NULL,
	PhoneId NUMBER(10) NOT NULL
)
/

CREATE SEQUENCE COMPANYPHONE_ID_SEQ START WITH 3
/

ALTER TABLE Person ADD CONSTRAINT FK_Person_Merged FOREIGN KEY (MergedToPersonId) REFERENCES Person(Id)
/
ALTER TABLE Person ADD CONSTRAINT FK_Person_Sup FOREIGN KEY (SupervisorId) REFERENCES Person(Id)
/
ALTER TABLE Person ADD CONSTRAINT FK_Person_Cc FOREIGN KEY (CareerCounselorId) REFERENCES Person(Id)
/
ALTER TABLE PersonCompany ADD CONSTRAINT FK_PC_Person FOREIGN KEY (PersonId) REFERENCES Person(Id)
/
ALTER TABLE PersonCompany ADD CONSTRAINT FK_PC_Company FOREIGN KEY (CompanyId) REFERENCES Company(Id)
/
ALTER TABLE PersonEmail ADD CONSTRAINT FK_PE_Person FOREIGN KEY (PersonId) REFERENCES Person(Id)
/
ALTER TABLE PersonEmail ADD CONSTRAINT FK_PE_Email FOREIGN KEY (EmailId) REFERENCES Email(Id)
/
ALTER TABLE CompanyEmail ADD CONSTRAINT FK_CE_Company FOREIGN KEY (CompanyId) REFERENCES Company(Id)
/
ALTER TABLE CompanyEmail ADD CONSTRAINT FK_CE_Email FOREIGN KEY (EmailId) REFERENCES Email(Id)
/
ALTER TABLE PersonPhone ADD CONSTRAINT FK_PP_Person FOREIGN KEY (PersonId) REFERENCES Person(Id)
/
ALTER TABLE PersonPhone ADD CONSTRAINT FK_PP_Phone FOREIGN KEY (PhoneId) REFERENCES Phone(Id)
/
ALTER TABLE CompanyPhone ADD CONSTRAINT FK_CP_Company FOREIGN KEY (CompanyId) REFERENCES Company(Id)
/
ALTER TABLE CompanyPhone ADD CONSTRAINT FK_CP_Phone FOREIGN KEY (PhoneId) REFERENCES Phone(Id)
/
