CREATE TABLE Person (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MergedToPersonId INT,
	FirstName VARCHAR(50),
	LastName VARCHAR(50),
	SupervisorId INT,
	CareerCounselorId INT,
	CreateDate DATE,
	FOREIGN KEY (MergedToPersonId) REFERENCES Person(Id),
	FOREIGN KEY (SupervisorId) REFERENCES Person(Id),
	FOREIGN KEY (CareerCounselorId) REFERENCES Person(Id)
);

CREATE TABLE Company (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name VARCHAR(100)
);

CREATE TABLE PersonCompany (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PersonId INT NOT NULL,
	CompanyId INT NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE,
	FOREIGN KEY(PersonId) REFERENCES Person(Id),
	FOREIGN KEY(CompanyId) REFERENCES Company(Id)
);

CREATE TABLE Email (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Address VARCHAR(250)
);

CREATE TABLE PersonEmail (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PersonId INT NOT NULL,
	EmailId INT NOT NULL,
	FOREIGN KEY(PersonId) REFERENCES Person(Id),
	FOREIGN KEY(EmailId) REFERENCES Email(Id)
);

CREATE TABLE CompanyEmail (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CompanyId INT NOT NULL,
	EmailId INT NOT NULL,
	FOREIGN KEY(CompanyId) REFERENCES Company(Id),
	FOREIGN KEY(EmailId) REFERENCES Email(Id)
);

CREATE TABLE Phone (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Number VARCHAR(16),
	Type INT
);

CREATE TABLE PersonPhone (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PersonId INT NOT NULL,
	PhoneId INT NOT NULL,
	FOREIGN KEY(PersonId) REFERENCES Person(Id),
	FOREIGN KEY(PhoneId) REFERENCES Phone(Id)
);

CREATE TABLE CompanyPhone (
	Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CompanyId INT NOT NULL,
	PhoneId INT NOT NULL,
	FOREIGN KEY(CompanyId) REFERENCES Company(Id),
	FOREIGN KEY(PhoneId) REFERENCES Phone(Id)
);
