CREATE TABLE Person (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	MergedToPersonId INTEGER,
	FirstName TEXT,
	LastName TEXT,
	SupervisorId INTEGER,
	CareerCounselorId INTEGER,
	CreateDate TEXT,
	FOREIGN KEY (MergedToPersonId) REFERENCES Person(Id),
	FOREIGN KEY (SupervisorId) REFERENCES Person(Id),
	FOREIGN KEY (CareerCounselorId) REFERENCES Person(Id)
);

CREATE TABLE Company (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT
);

CREATE TABLE PersonCompany (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	PersonId INTEGER NOT NULL,
	CompanyId INTEGER NOT NULL,
	StartDate TEXT NOT NULL,
	EndDate TEXT,
	FOREIGN KEY(PersonId) REFERENCES Person(Id),
	FOREIGN KEY(CompanyId) REFERENCES Company(Id)
);

CREATE TABLE Email (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Address TEXT
);

CREATE TABLE PersonEmail (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	PersonId INTEGER NOT NULL,
	EmailId INTEGER NOT NULL,
	FOREIGN KEY(PersonId) REFERENCES Person(Id),
	FOREIGN KEY(EmailId) REFERENCES Email(Id)
);

CREATE TABLE CompanyEmail (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	CompanyId INTEGER NOT NULL,
	EmailId INTEGER NOT NULL,
	FOREIGN KEY(CompanyId) REFERENCES Company(Id),
	FOREIGN KEY(EmailId) REFERENCES Email(Id)
);

CREATE TABLE Phone (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Number TEXT,
	Type INTEGER
);

CREATE TABLE PersonPhone (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	PersonId INTEGER NOT NULL,
	PhoneId INTEGER NOT NULL,
	FOREIGN KEY(PersonId) REFERENCES Person(Id),
	FOREIGN KEY(PhoneId) REFERENCES Phone(Id)
);

CREATE TABLE CompanyPhone (
	Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	CompanyId INTEGER NOT NULL,
	PhoneId INTEGER NOT NULL,
	FOREIGN KEY(CompanyId) REFERENCES Company(Id),
	FOREIGN KEY(PhoneId) REFERENCES Phone(Id)
);
