CREATE TABLE Person (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MergedToPersonId INT,
	FirstName NVARCHAR(50),
	LastName NVARCHAR(50),
	SupervisorId INT,
	CareerCounselorId INT,
	CreateDate DATE,
	FOREIGN KEY (MergedToPersonId) REFERENCES Person(Id),
	FOREIGN KEY (SupervisorId) REFERENCES Person(Id),
	FOREIGN KEY (CareerCounselorId) REFERENCES Person(Id)
);
GO

CREATE TABLE Company (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Name NVARCHAR(100)
);
GO

CREATE TABLE PersonCompany (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PersonId INT NOT NULL,
	CompanyId INT NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE,
	FOREIGN KEY(PersonId) REFERENCES Person(Id),
	FOREIGN KEY(CompanyId) REFERENCES Company(Id)
);
GO

CREATE TABLE Email (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Address NVARCHAR(250)
);
GO

CREATE TABLE PersonEmail (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PersonId INT NOT NULL,
	EmailId INT NOT NULL,
	FOREIGN KEY(PersonId) REFERENCES Person(Id),
	FOREIGN KEY(EmailId) REFERENCES Email(Id)
);
GO

CREATE TABLE CompanyEmail (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	CompanyId INT NOT NULL,
	EmailId INT NOT NULL,
	FOREIGN KEY(CompanyId) REFERENCES Company(Id),
	FOREIGN KEY(EmailId) REFERENCES Email(Id)
);
GO

CREATE TABLE Phone (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Number NVARCHAR(16),
	Type INT
);
GO

CREATE TABLE PersonPhone (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PersonId INT NOT NULL,
	PhoneId INT NOT NULL,
	FOREIGN KEY(PersonId) REFERENCES Person(Id),
	FOREIGN KEY(PhoneId) REFERENCES Phone(Id)
);
GO

CREATE TABLE CompanyPhone (
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	CompanyId INT NOT NULL,
	PhoneId INT NOT NULL,
	FOREIGN KEY(CompanyId) REFERENCES Company(Id),
	FOREIGN KEY(PhoneId) REFERENCES Phone(Id)
);
GO
