<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Sql\1-Create.sql" />
    <None Remove="Sql\2-Data.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sql\1-Create.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Sql\2-Data.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup-core" Version="6.1.1" />
    <PackageReference Include="dbup-oracle" Version="6.2.0" />
    <PackageReference Include="GraphQL.NewtonsoftJson" Version="8.8.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.200" />
    <PackageReference Include="Testcontainers.Oracle" Version="4.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\AdaskoTheBeAsT.Dapper.GraphQL\AdaskoTheBeAsT.Dapper.GraphQL.csproj" />
    <ProjectReference Include="..\..\..\src\AdaskoTheBeAsT.Dapper.GraphQL.Oracle\AdaskoTheBeAsT.Dapper.GraphQL.Oracle.csproj" />
  </ItemGroup>

</Project>
